version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  minio_SQL_connector:
    image: minio_sql_connector
    container_name: minio_sql_connector
    restart: always
    ports:
      - "3000:3000"  
    volumes:
      - ./config.js:/app/config.js

volumes:
  postgres_data: