version: '3.7'

services:
  trino:
    image: trinodb/trino:438
    container_name: trino
    ports:
      - "8081:8080"
      - "8443:8443"
    environment:
      - TRINO_ENVIRONMENT=production
      - TRINO_NODE_ID=trino
      - TRINO_DISCOVERY_URI=https://localhost:8443
      - TRINO_DISCOVERY_SERVER_ENABLED=true
    volumes:
     - ./config.properties:/etc/trino/config.properties
     - ./presto_keystore.jks:/etc/trino/presto_keystore.jks
     - ./password.db:/etc/password.db
     - ./group.txt:/etc/group.txt
     - ./rules.json:/etc/rules.json
     - ./password-authenticator.properties:/etc/trino/password-authenticator.properties
     - ./group-provider.properties:/etc/trino/group-provider.properties
     - ./access-control.properties:/etc/trino/access-control.properties
     - ./user-mapping.json:/etc/trino/user-mapping.json
     - trino-data:/data
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    container_name: keycloak
    ports:
      - "8080:8080"
    #env_file: .env
    #volumes:
    #  - ./minio-realm.json:/tmp/minio-realm.json

  platoform-simulator:
    image: platform-simulator:0.0.1
    container_name: platform-simulator 
    ports:
      - "5000:5000"

  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: minio server /data
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_DEFAULT_BUCKETS=test_bucket
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://host.docker.internal:8080/auth/realms/master/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=minio-app
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=
      - MINIO_IDENTITY_OPENID_SCOPES=openid,email
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=on
volumes:
  trino-data:
    driver: local
  minio-data:
    driver: local
