version: '3.7'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    container_name: keycloak
    ports:
      - "8080:8080"
    env_file: .env
    #volumes:
    #  - ./minio-realm.json:/tmp/minio-realm.json