version: '3.7'

services:
  trino:
    image: trinodb/trino:438
    container_name: trino
    ports:
      - "8081:8080"
      - "8443:8443"
    environment:
      - TRINO_ENVIRONMENT=production
      - TRINO_NODE_ID=trino
      - TRINO_DISCOVERY_URI=https://localhost:8443
      - TRINO_DISCOVERY_SERVER_ENABLED=true
    volumes:
     - ./config.properties:/etc/trino/config.properties
     - ./presto_keystore.jks:/etc/trino/presto_keystore.jks
     - ./password.db:/etc/password.db
     - ./group.txt:/etc/group.txt
     - ./rules.json:/etc/rules.json
     - ./password-authenticator.properties:/etc/trino/password-authenticator.properties
     - ./group-provider.properties:/etc/trino/group-provider.properties
     - ./access-control.properties:/etc/trino/access-control.properties
     - ./user-mapping.json:/etc/trino/user-mapping.json
     - trino-data:/data

volumes:
  trino-data:
    driver: local
